name: krishi_rakshak
description: "Farmers Disease Diagnostic and Regional Outbreak Reporting Portal"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  
  # Networking & HTTP
  http: ^1.2.0
  http_parser: ^4.0.2
  
  # Geolocation & Device
  geolocator: ^10.1.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  
  # UI & Styling
  google_fonts: ^6.1.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
